# Generated by Selenium IDE
import unittest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLuoshaoqitest(unittest.TestCase):
  def setUp(self):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def tearDown(self):
    self.driver.quit()
  
  def test_luoshaoqitest(self):
    self.driver.get("http://blog.luoshaoqi.cn/")
    self.driver.set_window_size(1550, 838)
    time.sleep(5)
    self.driver.find_element(By.LINK_TEXT, "Test123").click()
    self.driver.find_element(By.LINK_TEXT, "从头开始编写一个五子棋的博弈游戏(Java)(第三期)").click()

if __name__=="__main__":
    unittest.main()